### ISSUE TITLE
META.yml points at the wrong issue tracker

### ISSUE THREAD

**Issue by petdance** [gugod/Perl-Critic-TooMuchCode#4]
https://metacpan.org/pod/Perl::Critic::TooMuchCode links to https://rt.cpan.org/Public/Dist/Display.html?Name=Perl-Critic-TooMuchCode for the "Issues" link.

I believe you'll just need a `bugtracker` key below the `resources` key in META.yml, but I don't know how to do that in Build.PL.

**Comment by gugod** [comment]
https://metacpan.org/release/GUGOD/Perl-Critic-TooMuchCode-0.11

This is also fixed with release-0.11 and already effect metacpan. Thanks again @petdance !
